development:
  adapter: mysql2
  database: pizza_development
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

production:
  adapter: mysql2
  database: pizza_production
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

